// Generated by https://quicktype.io

export interface ResultCiudadanoAlerta {
    ok:     boolean;
    resp:   string;
    alerta: Alerta[];
}

export interface Alerta {
    id:          number;
    descripcion: string;
    lat:         number;
    lng:         number;
    foto:        null | string;
    fecha:       string;
    hora:        string;
    ciudadano:   number;
    tipo_alerta: number;
    derivado:    null;
    TipoAlertum: TipoAlertum;
}

export interface TipoAlertum {
    id:          number;
    nombre:      string;
    opcion_foto: number;
    icono:       Icono;
    img:         string;
    color:       string;
    estado:      number;
}

export enum Icono {
    MegaphoneOutline = "megaphone-outline",
}
